### PR TITLE
Finished VSTS project, dep. version updates, and lint config updates

### LINKED ISSUE #39: Finish VSTS-Task Project Type
Complete all scaffold content for the VSTS Task project type

### LINKED ISSUE #46: Update ESLint Rules
Extend the ESLint rules configuration (especially now that JSHint has been removed) to include all of the rules not covered by the ESLint:Recommended set

### LINKED ISSUE #90: Bug: Many scripts fail on scaffolded VSTS Task projects
- node version: all
- npm version: all
- yo version: all
- generator-version: 0.14.1-alpha, and possible previous
- os: all

This one is on me. VSTS task projects need npm scripts/configs/code updated so that the core transpile/lint/test tasks will pass in new projects

### LINKED ISSUE #96: Doc Updates
We've made a number of changes to the content/structure/etc. of projects that are scaffolded by the generator. Need to update the documentation accordingly

### PR DESCRIPTION
**Pull request by calebcartwright**
Opening this PR a little early to start dialog on eslint config per #46, other changes below (some still pending)

- [x] Updated to latest versions of shared and project specific dependencies in template content (also on gen. codebase)
- [x] Closes #90 - fixes npm script failures/issues in VSTS project
- [x] Closes #46 - Removes problematic eslint configs (quotes & max-statements) as they are covered in tslint
- [x] Closes #39 - Finally finishes the VSTS project type
- [x] Closes #96 - Updated relevant documentation to address the above

(edit) removed the 'no-merge' text at the beginning, as this is ready for merge now

### CODE REVIEW

File: generators/app/templates/chatbot/src/bot.ts [hunk 1]
```diff
@@ -1,16 +1,8 @@
 'use strict';
 
-// This is a temporary fix due to the way the TypeScript compiler currently functions
-// it converts single quotes to double quotes on import/require statements.
-/* tslint:disable:no-single-line-block-comment JSHint and ESLint need single line block comments */
-/* jshint quotmark:false */
```
Comment (calebcartwright) [inline generators/app/templates/chatbot/src/bot.ts]: @beverts312  We can remove (and no longer need) this stuff anymore due to new eslint config updates

**Comment by calebcartwright** [comment]
Well bummer.. Codeclimate is failing now that I am running linting against both the generator code and the templates. think I will just update the codeclimate config so that it ignores

File: generators/app/templates/boilerplate/eslintrc.js [hunk 2]
```diff
@@ -38,26 +39,26 @@ module.exports = {
         'linebreak-style': [
             'off'
         ],
-        quotes: [
-            'error',
-            'single'
-        ],
+        // quotes: [
```
Comment (calebcartwright) [inline generators/app/templates/boilerplate/eslintrc.js]: This one resolves the single vs. double quote issue that was created by TS taking our single quotes as input, and emitting them as double quotes in some places.

The TSLint rule is already enforcing consistency, so no need to fight this one

File: generators/app/templates/boilerplate/eslintrc.js [hunk 3]
```diff
@@ -38,26 +39,26 @@ module.exports = {
...
-        "max-statements": [
-            'error',
-            {
-                'max': 10
-            },
-            {
-                'ignoreTopLevelFunctions': false
-            }
-        ],
+        // "max-statements": [
```
Comment (calebcartwright) [inline generators/app/templates/boilerplate/eslintrc.js]: This is another one that generates false positives, especially on our test suites. TSLint allows us to specify that it should ignore the mocha grouping functions (suite, describe, etc. blocks), whereas eslint does not. Disabling this rule in eslint eliminates the need to add a disable line to each and every nested suite

File: generators/app/templates/boilerplate/gulp/gulp-config.js [hunk 4]
```diff
@@ -1,13 +1,14 @@
+/*eslint quotes: ["error", "single"]*/
```
Comment (calebcartwright) [inline generators/app/templates/boilerplate/gulp/gulp-config.js]: We only have a handful of true source js files that are generated by the templates. This line just enforces that we have single quotes in our source JS files (since eslint is no longer checking quotes & TSLint doesn't look at js.

The line below is a pointer to an issue that's being tracked in the Typescript repo to enable users to specify a flag/config/etc. to typescript compiler so that we can control whether or not it emits single or double quotes on generated code

File: generators/app/templates/boilerplate/gulp/tasks/test.js [hunk 5]
```diff
@@ -1,14 +1,16 @@
+/*eslint quotes: ["error", "single"]*/
+// Related to: https://github.com/Microsoft/TypeScript/issues/13270'
 'use strict';
 
-var gulp = require('gulp');
-var browserOpen = require('gulp-open');
-var istanbul = require('gulp-istanbul');
-var mocha = require('gulp-mocha');
-var nsp = require('gulp-nsp');
+const gulp = require('gulp');
```
Comment (calebcartwright) [inline generators/app/templates/boilerplate/gulp/tasks/test.js]: I also tried to go through our existing JS files to ensure we are following ES6 contentions instead of ES5

**Comment by calebcartwright** [comment]
@beverts312 - it just hit me as I was finishing off the documentation for the VSTS project type that the directory structure the generator creates does not jive well for multi-task scenarios. 

Ideally IMO all a user would need to do to add an additional task to his/her project/extension is to basically just create a subdirectory (and maybe add a task specific npm script), but the current layout is far from that..

I was going to just merge and publish to npm (especially since current version is broken) and finish the docs for the current structure, but I am struggling to convince myself to write documentation for something I know will become irrelevant in the very near future.

Question: how important is multi-task support, and should generator be "fixed" on this branch to support it now or shall we punt?

**Comment by calebcartwright** [comment]
I actually think subsequent (post initial scaffolding) creation of tasks might be the first candidate for a subcommand within the generator. although that might be more like release 18.x
